kitchen/urls.py
from django.urls import path

from kitchen.views import (
    IndexView,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    AssignToDishView,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,

)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path(
        "cooks/", CookListView.as_view(),
        name="cook-list",
    ),
    path(
        "cooks/<int:pk>/", CookDetailView.as_view(),
        name="cook-detail",
    ),
    path(
        "cooks/create/", CookCreateView.as_view(),
        name="cook-create"
    ),
    path(
        "cooks/<int:pk>/update/", CookUpdateView.as_view(),
        name="cook-update"
    ),
    path(
        "cooks/<int:pk>/delete/", CookDeleteView.as_view(),
        name="cook-delete"
    ),
    path(
        "dishes/", DishListView.as_view(),
        name="dish-list",
    ),
    path(
        "dishes/<int:pk>/", DishDetailView.as_view(),
        name="dish-detail"
    ),
    path(
        "dishes/create/", DishCreateView.as_view(),
        name="dish-create",
    ),
    path(
        "dishes/<int:pk>/update/", DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dishes/<int:pk>/delete/", DishDeleteView.as_view(),
        name="dish-delete",
    ),
    path(
        "dishes/<int:pk>/assigning/", AssignToDishView.as_view(),
        name="cook-assigning",
    ),
    path(
        "dish_types/", DishTypeListView.as_view(),
        name="dish-type-list"
    ),
    path(
        "dish_types/create/", DishTypeCreateView.as_view(),
        name="dish-type-create"
    ),
    path(
        "dish_types/<int:pk>/update/", DishTypeUpdateView.as_view(),
        name="dish-type-update"
    ),
    path(
        "dish_types/<int:pk>/delete/", DishTypeDeleteView.as_view(),
        name="dish-type-delete"
    ),
]

app_name = "kitchen"

restaurant_kitchen_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include

from kitchen.views import RegisterUserView, LoginView

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("", include("kitchen.urls", namespace="kitchen")),
                  path("accounts/login/", LoginView.as_view(), name="login"),
                  path("register/", RegisterUserView.as_view(), name="register"),
                  path("logout/", LogoutView.as_view(), name="logout"),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/footer.html
<footer class="footer pt-3 mt-2">
  <hr class="horizontal dark mb-4">
  <div class="container">
    <div class=" row">
      <div class="col-md-3 mb-4 ms-auto">
        <div>
          <h6 class="text-dark font-weight-bolder">Restaurant Kitchen System</h6>
        </div>
        <div>
          <h6 class="mt-3 mb-2 opacity-8">Social</h6>
          <ul class="d-flex flex-row ms-n3 nav">
            <li class="nav-item">
              <a class="nav-link pe-1" href="https://github.com/svitlana-savikhina?tab=repositoriesv" target="_blank">
                <i class="fab fa-github text-lg opacity-8"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-2 col-sm-6 col-6 mb-4">
        <div>
          <h6 class="text-success text-sm font-weight-bolder">Company</h6>
          <ul class="flex-column ms-n3 nav">
            <li class="nav-item">
              <a class="nav-link" href="">
                About Us
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="" target="_blank">
                Freebies
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="" target="_blank">
                Premium Tools
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="" target="_blank">
                Blog
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-2 col-sm-6 col-6 mb-4">
        <div>
          <h6 class="text-success text-sm font-weight-bolder">Resources</h6>
          <ul class="flex-column ms-n3 nav">
            <li class="nav-item">
              <a class="nav-link" href="" target="_blank">
                Illustrations
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="" target="_blank">
                Bits & Snippets
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="" target="_blank">
                Affiliate Program
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-2 col-sm-6 col-6 mb-4">
        <div>
          <h6 class="text-success text-sm font-weight-bolder">Help & Support</h6>
          <ul class="flex-column ms-n3 nav">
            <li class="nav-item">
              <a class="nav-link" href="" target="_blank">
                Contact Us
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="" target="_blank">
                Knowledge Center
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="" target="_blank">
                Custom Development
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="" target="_blank">
                Sponsorships
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-2 col-sm-6 col-6 mb-4 me-auto">
        <div>
          <h6 class="text-success text-sm font-weight-bolder">Legal</h6>
          <ul class="flex-column ms-n3 nav">
            <li class="nav-item">
              <a class="nav-link" href="" target="_blank">
                Terms & Conditions
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="" target="_blank">
                Privacy Policy
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="" target="_blank">
                Licenses (EULA)
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-12">
        <div class="text-center">
          <p class="my-4 text-sm">
            Restaurant Kitchen Service &copy;
            - Coded by <a target="_blank" href="https://github.com/svitlana-savikhina?tab=repositoriesv"
                          target="_blank">Svitlana Savikhina</a>.
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/includes/navigation-auth.html
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav
          class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid">
          <strong>Restaurant Kitchen Service</strong>
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse"
                  data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false"
                  aria-label="Toggle navigation">
            <span class="navbar-toggler-icon mt-2">
              <span class="navbar-toggler-bar bar1"></span>
              <span class="navbar-toggler-bar bar2"></span>
              <span class="navbar-toggler-bar bar3"></span>
            </span>
          </button>
          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
            <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
              <li class="nav-item ms-lg-auto">
                <a class="nav-link nav-link-icon me-2"
                   href="#" target="_blank">
                  <i class="fa fa-rocket me-1"></i>
                  <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                     data-bs-placement="bottom" title="Get Free Support">Support</p>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
    </div>
  </div>
</div>

templates/includes/navigation.html
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav
          class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid">
          <span class="fw-bold text-dark">
            Wellcome to our service, {{ user.username }}!
          </span>
          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
            <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
              <li class="nav-item mx-2">
                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"
                   href="{% url 'kitchen:cook-list' %}">
                  <span class="fw-bold text-dark">All Cooks</span>
                </a>
              <li class="nav-item mx-2">
                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"
                   href="{% url 'kitchen:dish-list' %}"><span class="fw-bold text-dark">All Dishes</span>
                </a>
              </li>
              <li class="nav-item  mx-2">
                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"
                   href="{% url 'kitchen:dish-type-list' %}">
                  <span class="fw-bold text-dark">All Dish Types</span>
                </a>
              </li>
              <li class="nav-item  mx-2">
                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center" href="/">
                  <span class="fw-bold text-success text-decoration-underline">Home</span>
                </a>
              </li>
              <li class="nav-item ms-lg-auto">
                <a class="nav-link nav-link-icon me-2" href="{% url 'login' %}">
                  <i class="fa fa-sign-out me-1"></i>
                  <p class="d-inline text-sm  z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                     data-bs-placement="bottom" title="Logout">Logout</p>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
    </div>
  </div>
</div>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination pagination-dark justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>{% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}





templates/includes/scripts.html
<script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>