kitchen/urls.py
from django.urls import path

from kitchen.views import (
    IndexView,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    AssignToDishView,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,

)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path(
        "cooks/", CookListView.as_view(),
        name="cook-list",
    ),
    path(
        "cooks/<int:pk>/", CookDetailView.as_view(),
        name="cook-detail",
    ),
    path(
        "cooks/create/", CookCreateView.as_view(),
        name="cook-create"
    ),
    path(
        "cooks/<int:pk>/update/", CookUpdateView.as_view(),
        name="cook-update"
    ),
    path(
        "cooks/<int:pk>/delete/", CookDeleteView.as_view(),
        name="cook-delete"
    ),
    path(
        "dishes/", DishListView.as_view(),
        name="dish-list",
    ),
    path(
        "dishes/<int:pk>/", DishDetailView.as_view(),
        name="dish-detail"
    ),
    path(
        "dishes/create/", DishCreateView.as_view(),
        name="dish-create",
    ),
    path(
        "dishes/<int:pk>/update/", DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dishes/<int:pk>/delete/", DishDeleteView.as_view(),
        name="dish-delete",
    ),
    path(
        "dishes/<int:pk>/assigning/", AssignToDishView.as_view(),
        name="cook-assigning",
    ),
    path(
        "dish_types/", DishTypeListView.as_view(),
        name="dish-type-list"
    ),
    path(
        "dish_types/create/", DishTypeCreateView.as_view(),
        name="dish-type-create"
    ),
    path(
        "dish_types/<int:pk>/update/", DishTypeUpdateView.as_view(),
        name="dish-type-update"
    ),
    path(
        "dish_types/<int:pk>/delete/", DishTypeDeleteView.as_view(),
        name="dish-type-delete"
    ),
]

app_name = "kitchen"

restaurant_kitchen_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include

from kitchen.views import RegisterUserView, LoginView

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("", include("kitchen.urls", namespace="kitchen")),
                  path("accounts/login/", LoginView.as_view(), name="login"),
                  path("register/", RegisterUserView.as_view(), name="register"),
                  path("logout/", LogoutView.as_view(), name="logout"),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kitchen/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class DishType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.PositiveIntegerField(null=True)

    class Meta:
        verbose_name = "cook"
        verbose_name_plural = "cooks"
        ordering = ["username"]

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("kitchen:cook-detail", kwargs={"pk": self.pk})


class Dish(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=7, decimal_places=2)
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE)
    cooks = models.ManyToManyField(Cook, related_name="dishes")

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

kitchen/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from kitchen.models import Cook, Dish


class BaseCookForm(forms.ModelForm):

    def clean_years_of_experience(self):
        years_of_experience = self.cleaned_data["years_of_experience"]

        if years_of_experience > 60:
            raise ValidationError(
                "Value must be less than or equal to 60"
            )
        return years_of_experience


class CookCreateForm(UserCreationForm, BaseCookForm):
    class Meta(UserCreationForm):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "years_of_experience",
        )


class CookUpdateForm(BaseCookForm):
    class Meta:
        model = Cook
        fields = ("first_name", "last_name", "years_of_experience",)


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Dish
        fields = "__all__"


class CookSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"}))


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}))


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}))


class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Email",
                "class": "form-control"
            }
        ))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password check",
                "class": "form-control"
            }
        ))

    class Meta:
        model = Cook
        fields = ("username", "email", "password1", "password2")


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))

kitchen/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic, View
from django.views.generic import TemplateView

from kitchen.forms import CookCreateForm, CookUpdateForm, DishForm, CookSearchForm, DishSearchForm, DishTypeSearchForm, \
    SignUpForm, LoginForm
from kitchen.models import Cook, DishType, Dish


class IndexView(TemplateView):
    template_name = "kitchen/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["num_cooks"] = Cook.objects.count()
        context["num_dishes"] = Dish.objects.count()
        context["num_dish_type"] = DishType.objects.count()

        num_visits = self.request.session.get("num_visits", 0)
        self.request.session["num_visits"] = num_visits + 1
        context["num_visits"] = num_visits + 1

        return context


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = CookSearchForm(initial={"username": username})
        return context

    def get_queryset(self):
        queryset = Cook.objects.all()
        form = CookSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreateForm
    success_url = reverse_lazy("kitchen:cook-list")


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookUpdateForm


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    template_name = "kitchen/cook_confirm_delete.html"
    success_url = reverse_lazy("kitchen:cook-list")


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    queryset = Dish.objects.all().select_related("dish_type")
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = Dish.objects.all()
        form = DishSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-list")
    form_class = DishForm


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-list")
    form_class = DishForm


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    template_name = "kitchen/dish_confirm_delete.html"
    success_url = reverse_lazy("kitchen:dish-list")


class AssignToDishView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    fields = []

    def post(self, request, *args, **kwargs):
        pk = kwargs.get("pk")
        dish = get_object_or_404(Dish, id=pk)
        if request.user in dish.cooks.all():
            dish.cooks.remove(request.user)
        else:
            dish.cooks.add(request.user)

        return redirect("kitchen:dish-detail", pk)


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    context_object_name = "dish_type_list"
    template_name = "kitchen/dish_type_list.html"
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishTypeSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = DishType.objects.all()
        form = DishTypeSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dish-type-list")
    template_name = "kitchen/dish_type_form.html"


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dish-type-list")
    template_name = "kitchen/dish_type_form.html"


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    template_name = "kitchen/dish_type_confirm_delete.html"
    success_url = reverse_lazy("kitchen:dish-type-list")


class LoginView(View):
    template_name = "registration/login.html"

    def get(self, request):
        form = LoginForm()
        return render(request, self.template_name, {"form": form})

    def post(self, request):
        form = LoginForm(request.POST)
        msg = None

        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("/")
            else:
                msg = 'Invalid credentials'
        else:
            msg = 'Error validating the form'

        return render(request, "registration/login.html", {"form": form, "msg": msg})


class RegisterUserView(View):
    template_name = "registration/register.html"

    def get(self, request):
        form = SignUpForm()
        return render(request, self.template_name, {"form": form, "msg": None, "success": False})

    def post(self, request):
        form = SignUpForm(request.POST)
        msg = None
        success = False

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)

            msg = "User created - please <a href='/accounts/login'>login</a>"
            success = True

        else:
            msg = 'Form is not valid'

        return render(request, "registration/register.html", {"form": form, "msg": msg, "success": success})

templates/kitchen/cook_confirm_delete.html
{% extends "base-fullscreen.html" %}

{% block content %}
  {% include "includes/navigation.html" %}
  <div class="container mt-7">
    <h2 class="text-center">Would you like to permanently remove this cook?</h2>
    <form action="" method="post">
      {% csrf_token %}
      <div class="d-flex justify-content-center mt-3">
        <input type="submit" value="Yes" class="btn btn-danger me-3">
        <a href="{% url 'kitchen:cook-list' %}" class="btn btn-secondary">No</a>
      </div>
    </form>
  </div>
{% endblock %}


templates/kitchen/cook_detail.html
{% extends "base-fullscreen.html" %}

{% block content %}
  {% include "includes/navigation.html" %}
  <div class="container mt-7">
    <h1>Username: {{ cook.username }}</h1>
    <div>
      <a href="{% url 'kitchen:cook-update' pk=cook.id %}" class="btn btn-success">Update</a>
      <a href="{% url 'kitchen:cook-delete' pk=cook.id %}" class="btn btn-danger">Delete cook</a>
    </div>
    <br>
    <p><strong>First name: </strong>{{ cook.first_name }}</p>
    <p><strong>Last name: </strong>{{ cook.last_name }}</p>
    <p><strong>Years of experience: </strong>{{ cook.years_of_experience }}</p>
    <p><strong>Email address: </strong>{{ cook.email }}</p>
    <div class="ml-3">
      <h4>Dishes:</h4>
      <table class="table table-bordered table-striped text-center table-hover additional-class">
        <tr>
          <th>ID</th>
          <th>Dish</th>
          <th>Dish Type</th>
        </tr>
        {% for dish in cook.dishes.all %}
          <tr>
            <td>{{ dish.id }}</td>
            <td>{{ dish.name }}</td>
            <td>{{ dish.dish_type }}</td>
          </tr>
        {% empty %}
          <p>No dish!</p>
        {% endfor %}
      </table>
    </div>
  </div>
{% endblock %}





templates/kitchen/cook_form.html
{% extends "base-fullscreen.html" %}
{% load crispy_forms_filters %}

{% block content %}
  {% include "includes/navigation.html" %}

  <div class="container text-center  mt-7">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <h1>{{ object|yesno:"Update,Create" }} Cook</h1>
        <form action="" method="post" novalidate>
          {% csrf_token %}
          {{ form | crispy }}
          <input type="submit" value="Submit" class="btn btn-dark">
        </form>
      </div>
    </div>
  </div>
{% endblock %}





templates/kitchen/cook_list.html
{% extends "base-fullscreen.html" %}
{% load crispy_forms_filters %}

{% block content %}
  {% include "includes/navigation.html" %}
  <div class="container text-center  mt-7">
    <h1>Cook List</h1>
    <div class="container additional-class">
      <h5>You can create a new cook</h5>
      <a href="{% url 'kitchen:cook-create' %}" class="btn btn-success">
        Create
      </a>
    </div>
  </div>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <form action="" method="get" class="row g-3 align-items-center">
          <div class="col-8">
            {{ search_form | crispy }}
          </div>
          <div class="col-4">
            <input class="btn btn-dark" type="submit" value="Search">
          </div>
        </form>
      </div>
    </div>
  </div>
  <br>
  {% if cook_list %}
    <table class="table table-bordered table-striped text-center table-hover">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Years of experience</th>
      </tr>
      {% for cook in cook_list %}
        <tr>
          <td>{{ cook.id }}</td>
          <td><a href="{{ cook.get_absolute_url }}" style="color: black;">{{ cook.username }} {% if user == cook %}
            (Me) {% endif %}</a></td>
          <td>{{ cook.first_name }}</td>
          <td>{{ cook.last_name }}</td>
          <td>{{ cook.years_of_experience }}</td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no cooks in this service</p>
  {% endif %}
{% endblock %}





templates/kitchen/dish-type_confirm_delete.html
{% extends "base.html" %}

{% block content %}
   <div class="container mt-7">
    <h2 class="text-center">Would you like to permanently remove this dish type?</h2>
      <form action="" method="post">
        {% csrf_token %}
          <div class="d-flex justify-content-center mt-3">
            <input type="submit" value="Yes" class="btn btn-danger me-3">
              <a href="{% url 'kitchen:dish-type-list' %}" class="btn btn-secondary">No</a>
           </div>
      </form>
   </div>
{% endblock %}

templates/kitchen/dish_confirm_delete.html
{% extends "base-fullscreen.html" %}

{% block content %}
  {% include "includes/navigation.html" %}
  <div class="container mt-7">
    <h2 class="text-center">Would you like to permanently remove this dish?</h2>
    <form action="" method="post">
      {% csrf_token %}
      <div class="d-flex justify-content-center mt-3">
        <input type="submit" value="Yes" class="btn btn-danger me-3">
        <a href="{% url 'kitchen:dish-list' %}" class="btn btn-secondary">No</a>
      </div>
    </form>
  </div>
{% endblock %}

templates/kitchen/dish_detail.html
{% extends "base-fullscreen.html" %}

{% block content %}
  {% include "includes/navigation.html" %}
  <div class="container mt-7">
    <h1>{{ dish.name }}</h1>
    <h2>({{ dish.dish_type.name }})</h2>
    <br>
    <div>
      <a href="{% url 'kitchen:dish-update' pk=dish.id %}" class="btn btn-success">
        Update
      </a>
      <a href="{% url 'kitchen:dish-delete' pk=dish.id %}" class="btn btn-danger">
        Delete
      </a>
    </div>
    <br>
    <h4>Description:</h4>
    {{ dish.description }}
    <br>
    <br>
    <div class="ml-3">
      <h4>Cooks:</h4>
      <table class="table table-bordered table-striped text-center table-hover additional-class">
        <tr>
          <th>Username</th>
          <th>First name</th>
          <th>Last name</th>
          <th>Years of experience</th>
        </tr>
        {% for cook_ in dish.cooks.all %}
          <tr>
            <td>{{ cook_.username }}</td>
            <td>{{ cook_.first_name }}</td>
            <td>{{ cook_.last_name }}</td>
            <td>{{ cook_.years_of_experience }}</td>
          </tr>
        {% endfor %}
      </table>
      <br>
      {% if user in dish.cooks.all %}
        <form action="{% url 'kitchen:cook-assigning' pk=dish.id %}" method="post">
          {% csrf_token %}
          <input type="submit" value=" Delete me from this dish" class="btn btn-danger">
        </form>
      {% else %}
        <form action="{% url 'kitchen:cook-assigning' pk=dish.id %}" method="post">
          {% csrf_token %}
          <input type="submit" value="Assign me to this dish" class="btn btn-success">
        </form>
      {% endif %}
    </div>
  </div>
{% endblock %}





templates/kitchen/dish_form.html
{% extends "base-fullscreen.html" %}
{% load crispy_forms_filters %}

{% block content %}
  {% include "includes/navigation.html" %}

  <div class="container text-center  mt-7">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <h1>{{ object|yesno:"Update,Create" }} Dish</h1>
        <form action="" method="post" novalidate>
          {% csrf_token %}
          {{ form | crispy }}
          <input type="submit" value="Submit" class="btn btn-dark">
        </form>
      </div>
    </div>
  </div>
{% endblock %}




templates/kitchen/dish_list.html
{% extends "base-fullscreen.html" %}
{% load crispy_forms_filters %}

{% block content %}
  {% include "includes/navigation.html" %}
  <div class="container text-center  mt-7">
    <h1>Dish List</h1>
    <div class="container">
      <h5>You can create a new dish</h5>
      <a href="{% url 'kitchen:dish-create' %}" class="btn btn-success">
        Create
      </a>
    </div>
  </div>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <form action="" method="get" class="row g-3 align-items-center">
          <div class="col-8">
            {{ search_form | crispy }}
          </div>
          <div class="col-4">
            <input class="btn btn-dark" type="submit" value="search">
          </div>
        </form>
      </div>
      {% if dish_list %}
        <table class="table table-bordered table-striped text-center table-hover">
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Dish type</th>
            <th>Price</th>
            <th>Description</th>
          </tr>
          {% for dish in dish_list %}
            <tr>
              <td>{{ dish.id }}</td>
              <td>
                <a href="{% url 'kitchen:dish-detail' pk=dish.id %}" style="color: black;">{{ dish.name }}</a>
              </td>
              <td>{{ dish.dish_type }}</td>
              <td>{{ dish.price }}</td>
              <td>{{ dish.description }}</td>
            </tr>
          {% endfor %}
        </table>
        </div>
        </div>
      {% else %}
        <p> There are no dishes in restaurant</p>
      {% endif %}
{% endblock %}


templates/kitchen/dish_type_confirm_delete.html
{% extends "base-fullscreen.html" %}
{% block content %}
  {% include "includes/navigation.html" %}
  <div class="container mt-7">
    <h2 class="text-center">Would you like to permanently remove this dish type?</h2>
    <form action="" method="post">
      {% csrf_token %}
      <div class="d-flex justify-content-center mt-3">
        <input type="submit" value="Yes" class="btn btn-danger me-3">
        <a href="{% url 'kitchen:dish-type-list' %}" class="btn btn-secondary">No</a>
      </div>
    </form>
  </div>
{% endblock %}

templates/kitchen/dish_type_form.html
{% extends "base-fullscreen.html" %}
{% load crispy_forms_filters %}

{% block content %}
  {% include "includes/navigation.html" %}
  <div class="container text-center  mt-7">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <h1>{{ object|yesno:"Update,Create" }} dish type</h1>
        <form action="" method="post" novalidate>
          {% csrf_token %}
          {{ form|crispy }}
          <input type="submit" value="Submit" class="btn btn-dark">
        </form>
      </div>
    </div>
  </div>
{% endblock %}



templates/kitchen/dish_type_list.html
{% extends "base-fullscreen.html" %}
{% load crispy_forms_filters %}

{% block content %}
  {% include "includes/navigation.html" %}
  <div class="container text-center  mt-7">
    <h1>Dish type List</h1>
    <div class="container">
      <h5>You can create a new dish</h5>
      <a href="{% url 'kitchen:dish-type-create' %}" class="btn btn-success">
        Create
      </a>
    </div>
  </div>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <form action="" method="get" class="row g-3 align-items-center">
          <div class="col-8">
            {{ search_form | crispy }}
          </div>
          <div class="col-4">
            <input class="btn btn-dark" type="submit" value="search">
          </div>
        </form>
      </div>
      {% if dish_type_list %}
        <table class="table table-bordered table-striped text-center table-hover">
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Update</th>
            <th>Delete</th>
          </tr>
          {% for type in dish_type_list %}
            <tr>
              <td>{{ type.id }}</td>
              <td>{{ type.name }}</td>
              <td><a style="color:seagreen" href="{% url 'kitchen:dish-type-update' pk=type.id %}">Update</a></td>
              <td><a style="color:red" href="{% url 'kitchen:dish-type-delete' pk=type.id %}">Delete</a></td>
            </tr>
          {% endfor %}
        </table>
      {% else %}
        <p>There are no dish types in restaurant</p>
      {% endif %}
    </div>
  </div>
{% endblock %}


templates/kitchen/index.html
{% extends "base-presentation.html" %}


{% block body_class %} index-page {% endblock body_class %}

{% block content %}

  <header class="header-2">
    <div class="page-header section-height-75 relative"
         style="background-image: url('{{ ASSETS_ROOT }}/img/kitchen.jpg')">
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white pt-3 mt-n5">
              Restaurant Kitchen Service
            </h1>
            <p class="text-white mt-3">
              The best kitchen service for managing<br>cooking processes
            </p>
          </div>
        </div>
      </div>
    </div>
  </header>
  <section class="pt-3 pb-2" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 z-index-2 border-radius-xl mt-n8 mx-auto py-3 blur shadow-blur">
          <div class="row">
            <div class="col-md-4 position-relative">
              <div class="p-2 text-center">
                <h1 class="text-success"><span id="state1" countTo="{{ num_dish_type }}">0</span>+</h1>
                <h5 class="mt-2">Dish types</h5>
                <p class="mt-2">Your favorite dish types</p>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4 position-relative">
              <div class="p-2 text-center">
                <h1 class="text-success"><span id="state2" countTo="{{ num_dishes }}">0</span>+</h1>
                <h5 class="mt-2">Dishes</h5>
                <p class="mt-2">Delicious dishes</p>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4">
              <div class="p-2 text-center">
                <h1 class="text-success" id="state3" countTo="{{ num_cooks }}">0</h1>
                <h5 class="mt-2">Cooks</h5>
                <p class="mt-2">Experienced chefs</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <div class="pt-3 d-flex align-items-center justify-content-center">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h7>You have visited this page
            {{ num_visits }} time{{ num_visits|pluralize }}.
          </h7>

        </div>
      </div>
    </div>
  </div>



  <!-- -------   END PRE-FOOTER 2 - simple social line w/ title & 3 buttons    -------- -->

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}

  <script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>
  <script type="text/javascript">
    if (document.getElementById('state1')) {
      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
      if (!countUp.error) {
        countUp.start();
      } else {
        console.error(countUp.error);
      }
    }
    if (document.getElementById('state2')) {
      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
      if (!countUp1.error) {
        countUp1.start();
      } else {
        console.error(countUp1.error);
      }
    }
    if (document.getElementById('state3')) {
      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
      if (!countUp2.error) {
        countUp2.start();
      } else {
        console.error(countUp2.error);
      };
    }

  </script>
{% endblock javascripts %}

